# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Social_Network_Project' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Social_Network_Project

pod 'SnapKit', '~> 4.0.0'
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'LZViewPager'
pod 'SideMenu'

  target 'Social_Network_ProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Social_Network_ProjectUITests' do
    # Pods for testing
  end

end
